version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

environment:

jobs:
    build:
        working_directory: ~/CircleCiAutomation
        docker:
            - image: circleci/ruby:2.6.3-stretch-node
            - image: selenium/standalone-chrome-debug:3.141.59-20200525
        steps:
            - checkout
            - run: npm install appium
            - run: gem install bundler:2.1.4
            - run: bundle install
            - run: bundle exec cucumber -p mobile
            - store_artifacts:
              path: tmp/screenshots
