version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

environment:

jobs:
    build:
        working_directory: ~/CircleCiAutomation
        docker:
            - image: circleci/ruby:2.6.3-stretch-node
            - image: selenium/standalone-chrome-debug:3.141.59-20200525
        steps:
            - checkout
            - run: gem install bundler:2.1.4
            - run: bundle install
            - run: bundle exec cucumber -p docker
            - run: bundle exec cucumber -p mobile
            - run:
                name: Save test results
                command: |
                  mkdir -p ~/cucumber
                  bundle exec cucumber --format pretty --format html --out ~/cucumber/tests.html
                when: always
            - store_test_results:
                path: ~/cucumber
            - store_artifacts:
                path: ~/cucumber

              - run:
                  name: Save Report
                  command: |

                    bundle exec cucumber --format pretty --format html --out ~/report/Automation_Full_Report.html
                  when: always
              - store_test_results:
                  path: ~/report
              - store_artifacts:
                  path: ~/report
