version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

environment:
  # Customize the JVM maximum heap limit
ANDROID_HOME: /usr/local/android-sdk-linux


jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: npm install appium
      - run: gem install bundler:2.1.4
      - run: bundle install
      - run: appium -a 127.0.0.1 -p 4723
      - run: emulator -avd circleci-android29
      - run: bundle exec cucumber -p mobile
