version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

environment:

jobs:
    build:
        working_directory: ~/CircleCiAutomation
        docker:
            - image: circleci/ruby:2.6.3-stretch-node
            - image: codeception/codeceptjs
            depends_on:
              - chrome
            volumes:
              - .:/tests
        chrome:
          image: selenium/standalone-chrome:3.8.1-bohrium
          ports:
            - '4444'
            - '5900'
        steps:
            - checkout
            - run: npm install appium
            - run: gem install bundler:2.1.4
            - run: bundle install
            - run: bundle exec cucumber -p docker
